package spd.spring.camp.team3.domain.enums;

public enum AnimalType {
    BEAR, BISON, CHEETAH, COYOTE, CROW, DEER, DINGO, DUCK, EAGLE, ELEPHANT,
    FOX, GIRAFFE, HAWK, HIPOPOTAMO, HORSE, JAGUAR, KANGAROO, KOALA, LAMA,
    LION, LYNX, MOOSE, PANDA, PANTHER, PIG, PORCUPINE, PORPOISING, PUMA,
    PYTHON, RHINOCEROS, TIGER, WEASEL, WOLF, ZEBRA;
}